Fixed the iOS build when user does not have elevated permissions
expo/turtle pull request #283
Opened 2020-12-08 23:38 UTC by lochiego

The use of sudo does not appear to be necessary to execute 'xcrun simctl list'.

### Checklist
- [x] I've read the [Contribution Guidelines](https://github.com/expo/turtle/blob/master/CONTRIBUTING.md).
- [x] I've updated the [CHANGELOG](https://github.com/expo/turtle/blob/master/CHANGELOG.md) if necessary.
- [x] I've ensured the unit and smoke tests are still passing - either by running `yarn test:unit` and `yarn test:smoke:[ios|android]` or by checking the appropriate CircleCI builds' statuses.
- [x] **I've manually tested whether the changes I made work as expected.**

### Motivation and Context
In our build environment the user running turtle does not have elevated permissions. We performed all the setup steps using an administrative account, but have a dedicated, limited user account for the actual CI builds we perform using Jenkins.

We had no troubles with our build prior to release 0.19.1, which introduced a fix for building with Xcode 12.1. Following this release, our builds started failing. Perhaps it is just our environment, but we have no issues executing xcrun without elevated permissions. At this point we are building with Xcode 12.2 successfully using this change.

### Description
Removed the use of 'sudo' to run 'xcrun simctl list' as introduced in 0.19.1.
We tested this patch in place by updating the javascript from package freshly-installed via yarn and executing our build job, which did not overwrite the updated package code. We checked that the build succeeded, and confirmed that the JS we edited was not overwritten by a fresh copy of the package in the process of the build.

2020-12-09 15:09 UTC, dsokal commented
Thanks for the contribution @lochiego and sorry for breaking your distribution pipeline!

I just verified that `xcrun simctl list` (without sudo) executes successfully on our build VMs. This means we can probably drop sudo. However, I'm not sure if it was intended to run the command with elevated permissions. @bbarthec @wkozyra95 what do think?

2020-12-09 15:28 UTC, bbarthec approved these changes
I delegate checking this PR to @wkozyra95 as he's the author of this particular fix.
As long as it's not breaking our build services I'm ok with it 👍

2020-12-09 15:43 UTC, wkozyra95 requested changes
We need to run that with sudo on our workers, but in cli this part is not necessary. Can you wrap that call with if statement that checks whether it's run on CI?

2020-12-09 15:45 UTC, dsokal commented
@wkozyra95 why do we need sudo?

2020-12-09 15:53 UTC, wkozyra95 commented
You can check the value of that env https://github.com/expo/turtle/blob/master/src/bin/env.ts

2020-12-09 16:31 UTC, lochiego commented
Thanks for the direction, @wkozyra95! I've added the requested change.

2020-12-10 09:47 UTC, wkozyra95 approved these changes

2020-12-10 09:47 UTC, merged